### ISSUE TITLE
Pentadactyl updates.

### ISSUE THREAD

**Issue by PTNobel** [willsALMANJ/pentadactyl-signed#1]
Will the releases be updated to reflect the last month of Pentadactyl development?

**Comment by vyp** [comment]
https://github.com/5digits/dactyl/issues/99#issuecomment-247907565

**Comment by PTNobel** [comment]
@vyp Sorry, I missed that. I'll delete this now

**Comment by vyp** [comment]
No worries! :)

**Comment by PTNobel** [comment]
Actually looks like issues can't be deleted... I'll have to just close it.

**Comment by wshanks** [comment]
No problem. It is updated now. I switched back from my fork to the 5digits repo since it is working now.

**Comment by congma** [comment]
Sorry for bumping a closed issue, but it might be useful to look at 5digits/dactyl#176 and 5digits/dactyl#178.

**Comment by wshanks** [comment]
Okay, since Firefox 49 just came out today, I switched back to my own fork and merged in those patches. I will switch back to upstream after it fixes the problems with Firefox 49.

**Comment by congma** [comment]
Is release 7295 built from your fork with fixes e.g. 5digits/dactyl#176 merged in?  The xpi doesn't seem so (?)

**Comment by wshanks** [comment]
It is built from here: https://github.com/willsALMANJ/dactyl/commits/master It's just 5digits/dactyl with the two pull requests from zbinlin merged in. What doesn't seem right?

**Comment by congma** [comment]
By unzipping the 7295 xpi (downloaded from the "Releases" section of the project page) and inspecting the contents, namely the file `chrome/pentadactyl/content/config.js`, I can see, for example, line 206 which suggests to me the latest patches weren't picked up.  Can you confirm this?

Although right now I'm not sure if 5digits/dactyl#176 is better than, for example, tweaking the `complete` setting in pentadactyl (see #2), it looks like there might be a build issue, and the commits somehow didn't make it to the xpi.

**Comment by wshanks** [comment]
Yeah, 7295 somehow did not have the changes. It must be something about hg-git that I don't understand. `hg log` show the commits as merged and `hg status` showed no changed files but the files in the working tree did not have the changes from the merged pull requests. I should probably switch the script just to increment the version number each time and use a git repo. Right now it uses `hg-git` to clone the GitHub repo into an hg repo so that it can base the version number off the hg revision number like the old nightly builds did. That didn't work as well as I wanted because the hg revision numbers I get are slightly different from the nightly build numbers any way (possibly because the nightly builds used the real hg repo and the conversion to git and back to hg results in different numbers).

**Comment by PTNobel** [comment]
I hate to be a bother, but it looks like this repository has fallen out of date again, is there anything that could be done to help keep this up-to-date?

**Comment by wshanks** [comment]
Sorry about that. I will update it soon. I follow the dactyl repo along with several other repos that don't require any action on my part in my RSS reader. It seems like the rare dactyl updates slip through with the updates to the other repos that are more frequent because looking back I do see them in my feed. I tried changing the title of the dactyl feed so it stands out more from the other GitHub repo feeds. Maybe that will help. Feel free to keep opening an issue though if it seems like I missed something.

**Comment by wshanks** [comment]
7300 has been working for me and I haven't heard any complaints so far, so I will close this again for now.
