### ISSUE TITLE
can't install on FF57.0.1

### ISSUE THREAD

**Issue by mMontu** [willsALMANJ/pentadactyl-signed#6]
First of all, thanks for maintaining this repo! I've been relying on it for some time now

I've just tried to upgrade to Firefox 57.0.1, but the latest version here (7310) isn't compatible.
Do you intend to release an update soon?

**Comment by pink-mist** [comment]
I believe the changes that have happened in FF 57 have completely removed the entire foundation pentadactyl was built upon. I don't believe pentadactyl will work without a complete rewrite. And even then I'm not sure the new stuff that's replaced the old stuff in FF 57 would even allow most of the things pentadactyl does. If you use FF 57 or later, I don't think there's much hope of being able to use pentadactyl at all.

**Comment by mMontu** [comment]
Thanks for the lightning quick response!

That's bad news... I think I'm going to stick with FF 56 until some alternative is stable (e.g.: [trydactyl](https://github.com/cmcaine/tridactyl)).

**Comment by wshanks** [comment]
Yes, if you are already aware of tridactyl, then I don't think I can give you many more pointers on where to go. Personally, I am using Vimium-FF for now, but keeping tabs on the other projects. I tried Saka Key for a while but it had some rough edges that were not present in Vimium-FF. My biggest pet peeve is not being able to use keybindings while a page is loading because the keybindings have to be loaded in the page content with WebExtensions. I hope that will eventually be fixed in [this ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1215061).

I haven't followed Firefox development very closely. Version 57 is where Mozilla gave itself permission to disable XUL addons and start breaking things. If they haven't broken things yet, I think it is possible to turn XUL addons back on in the nightly version or in a release if you set the right compilation flags -- but it isn't really worth the trouble because Pentadactyl will break eventually if it hasn't broken yet.
